#
# Created on Tue May 12 2020
#
# @Auther:- Parth Virani
# Copyright (c) 2020 Oneclick
# my variables are ${myvar1} and ${myvar2}
#
server:
    port: 4040

db:
    type: "postgres"

env: 
    name: "prod"

jwt:
    ExpireIn: 1576800000
    SecretKey: "mySecre@tKey"

email:
    # host: "smtpout.secureserver.net"
    # user: "suresh@itoneclick.com"
    # pass: "Oneclick1@"
    # port: 465
    # secure: true
    # from: '"laytrip" <no-reply@laytrip.com>'
    # BCC:  'suresh@itoneclick.com'
    # admin: 'suresh@itoneclick.com'
    host: "smtp.office365.com"
    user: "no-reply@laytrip.com"
    pass: "Autoanswer21!"
    port: 587
    secure: true
    from: '"Laytrip Customer Service" <no-reply@laytrip.com>'
    BCC:  'suresh@itoneclick.com,gaurav@itoneclick.com,hitendra@laytrip.com,ashfaq@itoneclick.com,customerservice@laytrip.com'
    admin: 'suresh@itoneclick.com,jimeet@itoneclick.com'
    contactUs: 'contactus@laytrip.com'
    customerService: 'customerservice@laytrip.com'
    

Sentry:
    DSN: "https://ae1830da5d4744fa9a03efeff65d68c7@o399378.ingest.sentry.io/5256424"

AWS:
    accessKeyId: 'AKIAI6MH7IDCFQQYBGOA'
    secretAccessKey: '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'

fcmServerKey: "AAAAJAgdxc0:APA91bHvxPQRHIG3uxmbn6GXXjny1kgZuTgootgE1ZuJdeAw1UwnMPIZYJPGIsXasOmK5kGtmA7Ll_WPYYvEu6L4daCwzug1ZdiMgKaDt14DDNfITQbeePZiU6OpqYSKZYzbE0HqYnN7"

webNotificationkeys:
    publicKey: 'BMWEQPsZU4d0Le2OKMiM7S7ZUvnpaBj5WpJuJuVshYjzHWsCwaFgHjm5FpT2zjexvyqPZyvSTqh_g7pF2fjbS2Q'
    privateKey: 'pwDOYDpxsPqj2wQq0udzPl20v4R5qub7Z2idsREOWFU'
    mailTo : 'mailto:example@yourdomain.org'
    icon : 'assets/main-page-logo-small-hat.png'

twilio:
    accountSid: "AC080cf0989448504dcfafe87401fa32af"
    authToken: "8e64f879600ab3c26d45e451b0230109"
    smsNumber: "+12623261171"

cronUserId: "839aaa9a-03b2-4c22-a02e-a6a4b067db34"    