server:
  port: 4040

db:
    type: "postgres"
    port: 5432
    username: "postgres"
    host: "laytrip-dev.co7ivhdiz1jp.us-east-2.rds.amazonaws.com"
    database: "laytrip"
    password: "nOEbFEONMcWpZNPzdcQ1"
    synchronize: false

ppn:
    url: "https://api-sandbox.rezserver.com/api/hotel/"