#
# Created on Tue May 12 2020
#
# @Auther:- Parth Virani
# Copyright (c) 2020 Oneclick
# my variables are ${myvar1} and ${myvar2}
#

db:
    type: "postgres"
    port: 5432
    username: "postgres"
    host: "localhost"
    database: "laytravel"
    synchronize: true

jwt:
    secret: 'topSecret51'

mystifly:
         account_number: "MCN001506"
         password : "MWR2018_xml"
         target: "Test"
         user_name: "MWR_XML"
         url: "http://onepointdemo.myfarebox.com/V2/OnePoint.svc"

