export const allAirpots= [
	{
		"id" : 263,
		"name" : "All Airports",
		"code" : "ALY",
		"latitude" : 31.18,
		"longitude" : 29.95,
		"city" : "Alexandria",
		"country" : "Egypt",
		"icao" : "HEAX",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 278,
		"name" : "All Airports",
		"code" : "AMM",
		"latitude" : 31.72,
		"longitude" : 35.99,
		"city" : "Amman",
		"country" : "Jordan",
		"icao" : "OJAI",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 424,
		"name" : "All Airports",
		"code" : "ATL",
		"latitude" : 33.64,
		"longitude" : -84.43,
		"city" : "Atlanta, GA",
		"country" : "USA",
		"icao" : "KATL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 544,
		"name" : "All Airports",
		"code" : "BAK",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Baku",
		"country" : "Azerbaijan",
		"icao" : "",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 656,
		"name" : "All Airports",
		"code" : "BER",
		"latitude" : 52.31,
		"longitude" : 13.24,
		"city" : "Berlin",
		"country" : "Germany",
		"icao" : "\\\\N",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 683,
		"name" : "All Airports",
		"code" : "BFS",
		"latitude" : 54.66,
		"longitude" : -6.22,
		"city" : "Belfast",
		"country" : "United Kingdom",
		"icao" : "EGAA",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 740,
		"name" : "All Airports",
		"code" : "BHZ",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Belo Horizonte",
		"country" : "Brazil",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 783,
		"name" : "All Airports",
		"code" : "BJS",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Beijing",
		"country" : "China",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 802,
		"name" : "All Airports",
		"code" : "BKK",
		"latitude" : 13.68,
		"longitude" : 100.75,
		"city" : "Bangkok",
		"country" : "Thailand",
		"icao" : "VTBS",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 970,
		"name" : "All Airports",
		"code" : "BRU",
		"latitude" : 50.90,
		"longitude" : 4.48,
		"city" : "Brussels",
		"country" : "Belgium",
		"icao" : "EBBR",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1033,
		"name" : "All Airports",
		"code" : "BUE",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Buenos Aires",
		"country" : "Argentina",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1037,
		"name" : "All Airports",
		"code" : "BUH",
		"latitude" : 48.04,
		"longitude" : 10.72,
		"city" : "Bucharest",
		"country" : "Romania",
		"icao" : "BUCH",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1139,
		"name" : "All Airports",
		"code" : "BZE",
		"latitude" : 17.54,
		"longitude" : -88.31,
		"city" : "Belize City",
		"country" : "Belize",
		"icao" : "MZBZ",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1330,
		"name" : "All Airports",
		"code" : "CHI",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Chicago",
		"country" : "USA",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1426,
		"name" : "All Airports",
		"code" : "CLT",
		"latitude" : 35.21,
		"longitude" : -80.94,
		"city" : "Charlotte",
		"country" : "USA",
		"icao" : "KCLT",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1435,
		"name" : "All Airports",
		"code" : "CMB",
		"latitude" : 7.18,
		"longitude" : 79.88,
		"city" : "Colombo",
		"country" : "Sri Lanka",
		"icao" : "VCBI",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1442,
		"name" : "All Airports",
		"code" : "CMH",
		"latitude" : 40.00,
		"longitude" : -82.89,
		"city" : "Columbus",
		"country" : "USA",
		"icao" : "KCMH",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1518,
		"name" : "All Airports",
		"code" : "CPH",
		"latitude" : 55.62,
		"longitude" : 12.66,
		"city" : "Copenhagen",
		"country" : "Denmark",
		"icao" : "EKCH",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1782,
		"name" : "All Airports",
		"code" : "DFW",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Dallas",
		"country" : "USA",
		"icao" : "",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1905,
		"name" : "All Airports",
		"code" : "DOM",
		"latitude" : 15.55,
		"longitude" : -61.30,
		"city" : "Dominica",
		"country" : "Dominica",
		"icao" : "TDPD",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1959,
		"name" : "All Airports",
		"code" : "DTT",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Detroit",
		"country" : "USA",
		"icao" : "",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 1994,
		"name" : "All Airports",
		"code" : "DXB",
		"latitude" : 25.25,
		"longitude" : 55.36,
		"city" : "Dubai",
		"country" : "United Arab Emirates",
		"icao" : "OMDB",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 2174,
		"name" : "All Airports",
		"code" : "EPS",
		"latitude" : 19.20,
		"longitude" : -69.43,
		"city" : "Samana",
		"country" : "Dominican Republic",
		"icao" : "MDAB",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 2218,
		"name" : "All Airports",
		"code" : "ETH",
		"latitude" : 29.56,
		"longitude" : 34.96,
		"city" : "Eilat",
		"country" : "Israel",
		"icao" : "LLET",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 2340,
		"name" : "All Airports",
		"code" : "FIH",
		"latitude" : -4.39,
		"longitude" : 15.44,
		"city" : "Kinshasa",
		"country" : "Democratic Republic Of Congo",
		"icao" : "FZAA",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 2390,
		"name" : "All Airports",
		"code" : "FNA",
		"latitude" : 8.62,
		"longitude" : -13.20,
		"city" : "Freetown",
		"country" : "Sierra Leone",
		"icao" : "GFLL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 2421,
		"name" : "All Airports",
		"code" : "FRA",
		"latitude" : 50.03,
		"longitude" : 8.54,
		"city" : "Frankfurt",
		"country" : "Germany",
		"icao" : "EDDF",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 2643,
		"name" : "All Airports",
		"code" : "GLA",
		"latitude" : 55.87,
		"longitude" : -4.43,
		"city" : "Glasgow",
		"country" : "United Kingdom",
		"icao" : "EGPF",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 3058,
		"name" : "All Airports",
		"code" : "HOU",
		"latitude" : 29.65,
		"longitude" : -95.28,
		"city" : "Houston",
		"country" : "USA",
		"icao" : "KHOU",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 3211,
		"name" : "All Airports",
		"code" : "IEV",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Kiev",
		"country" : "Ukraine",
		"icao" : "",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 3366,
		"name" : "All Airports",
		"code" : "IST",
		"latitude" : 40.98,
		"longitude" : 28.81,
		"city" : "Istanbul",
		"country" : "Turkey",
		"icao" : "LTBA",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 3531,
		"name" : "All Airports",
		"code" : "JKT",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Jakarta",
		"country" : "Indonesia",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 3555,
		"name" : "All Airports",
		"code" : "JNB",
		"latitude" : -26.14,
		"longitude" : 28.25,
		"city" : "Johannesburg",
		"country" : "South Africa",
		"icao" : "FAJS",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4061,
		"name" : "All Airports",
		"code" : "KUL",
		"latitude" : 2.75,
		"longitude" : 101.71,
		"city" : "Kuala Lumpur",
		"country" : "Malaysia",
		"icao" : "WMKK",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4163,
		"name" : "All Airports",
		"code" : "LAX",
		"latitude" : 33.94,
		"longitude" : -118.41,
		"city" : "Los Angeles",
		"country" : "USA",
		"icao" : "KLAX",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4419,
		"name" : "All Airports",
		"code" : "LON",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "London",
		"country" : "United Kingdom",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4685,
		"name" : "All Airports",
		"code" : "MDE",
		"latitude" : 6.16,
		"longitude" : -75.42,
		"city" : "Medellin",
		"country" : "Colombia",
		"icao" : "SKRG",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4719,
		"name" : "All Airports",
		"code" : "MEL",
		"latitude" : -37.67,
		"longitude" : 144.84,
		"city" : "Melbourne",
		"country" : "Australia",
		"icao" : "YMML",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4732,
		"name" : "All Airports",
		"code" : "MEX",
		"latitude" : 19.44,
		"longitude" : -99.07,
		"city" : "Mexico City",
		"country" : "Mexico",
		"icao" : "MMMX",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4808,
		"name" : "All Airports",
		"code" : "MIA",
		"latitude" : 25.79,
		"longitude" : -80.29,
		"city" : "Miami",
		"country" : "USA",
		"icao" : "KMIA",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4819,
		"name" : "All Airports",
		"code" : "MIL",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Milan",
		"country" : "Italy",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4907,
		"name" : "All Airports",
		"code" : "MLW",
		"latitude" : 6.29,
		"longitude" : -10.76,
		"city" : "Monrovia",
		"country" : "Liberia",
		"icao" : "GLMR",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 4982,
		"name" : "All Airports",
		"code" : "MOW",
		"latitude" : 55.76,
		"longitude" : 37.62,
		"city" : "Moscow",
		"country" : "Russian Federation",
		"icao" : "\\\\N",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5112,
		"name" : "All Airports",
		"code" : "MTY",
		"latitude" : 25.78,
		"longitude" : -100.11,
		"city" : "Monterrey",
		"country" : "Mexico",
		"icao" : "MMMY",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5297,
		"name" : "All Airports",
		"code" : "NBO",
		"latitude" : -1.32,
		"longitude" : 36.93,
		"city" : "Nairobi",
		"country" : "Kenya",
		"icao" : "HKJK",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5366,
		"name" : "All Airports",
		"code" : "NGO",
		"latitude" : 34.86,
		"longitude" : 136.81,
		"city" : "Nagoya",
		"country" : "Japan",
		"icao" : "RJGG",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5470,
		"name" : "All Airports",
		"code" : "NOU",
		"latitude" : -22.01,
		"longitude" : 166.21,
		"city" : "Noumea",
		"country" : "New Caledonia",
		"icao" : "NWWW",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5571,
		"name" : "All Airports",
		"code" : "NYC",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "New York",
		"country" : "USA",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5774,
		"name" : "All Airports",
		"code" : "ORL",
		"latitude" : 28.55,
		"longitude" : -81.33,
		"city" : "Orlando",
		"country" : "USA",
		"icao" : "KORL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5790,
		"name" : "All Airports",
		"code" : "OSA",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Osaka",
		"country" : "Japan",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5800,
		"name" : "All Airports",
		"code" : "OSL",
		"latitude" : 60.19,
		"longitude" : 11.10,
		"city" : "Oslo",
		"country" : "Norway",
		"icao" : "ENGM",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5897,
		"name" : "All Airports",
		"code" : "PAR",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Paris",
		"country" : "France",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 5919,
		"name" : "All Airports",
		"code" : "PBM",
		"latitude" : 5.45,
		"longitude" : -55.19,
		"city" : "Paramaribo",
		"country" : "Suriname",
		"icao" : "SMJP",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6024,
		"name" : "All Airports",
		"code" : "PHC",
		"latitude" : 5.02,
		"longitude" : 6.95,
		"city" : "Port Harcourt",
		"country" : "Nigeria",
		"icao" : "DNPO",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6044,
		"name" : "All Airports",
		"code" : "PHX",
		"latitude" : 33.43,
		"longitude" : -112.01,
		"city" : "Phoenix",
		"country" : "USA",
		"icao" : "KPHX",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6306,
		"name" : "All Airports",
		"code" : "PTY",
		"latitude" : 9.07,
		"longitude" : -79.38,
		"city" : "Panama City",
		"country" : "Panama",
		"icao" : "MPTO",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6530,
		"name" : "All Airports",
		"code" : "REK",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Reykjavik",
		"country" : "Iceland",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6578,
		"name" : "All Airports",
		"code" : "RIO",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Rio De Janeiro",
		"country" : "Brazil",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6655,
		"name" : "All Airports",
		"code" : "ROM",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Rome",
		"country" : "Italy",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6776,
		"name" : "All Airports",
		"code" : "SAO",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Sao Paulo",
		"country" : "Brazil",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6856,
		"name" : "All Airports",
		"code" : "SDQ",
		"latitude" : 18.43,
		"longitude" : -69.67,
		"city" : "Santo Domingo",
		"country" : "Dominican Republic",
		"icao" : "MDSD",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6866,
		"name" : "All Airports",
		"code" : "SEA",
		"latitude" : 47.45,
		"longitude" : -122.31,
		"city" : "Seattle",
		"country" : "USA",
		"icao" : "KSEA",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6877,
		"name" : "All Airports",
		"code" : "SEL",
		"latitude" : 37.56,
		"longitude" : 126.79,
		"city" : "Seoul",
		"country" : "Korea",
		"icao" : "\\\\N",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6942,
		"name" : "All Airports",
		"code" : "SHA",
		"latitude" : 31.20,
		"longitude" : 121.34,
		"city" : "Shanghai",
		"country" : "China",
		"icao" : "ZSSS",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 6982,
		"name" : "All Airports",
		"code" : "SIN",
		"latitude" : 1.35,
		"longitude" : 103.99,
		"city" : "Singapore",
		"country" : "Singapore",
		"icao" : "WSSS",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7009,
		"name" : "All Airports",
		"code" : "SJO",
		"latitude" : 9.99,
		"longitude" : -84.21,
		"city" : "San Jose",
		"country" : "Costa Rica",
		"icao" : "MROC",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7016,
		"name" : "All Airports",
		"code" : "SJU",
		"latitude" : 18.44,
		"longitude" : -66.00,
		"city" : "San Juan",
		"country" : "Puerto Rico",
		"icao" : "TJSJ",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7159,
		"name" : "All Airports",
		"code" : "SPK",
		"latitude" : 42.79,
		"longitude" : 141.67,
		"city" : "Sapporo",
		"country" : "Japan",
		"icao" : "RJCJ",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7222,
		"name" : "All Airports",
		"code" : "SRZ",
		"latitude" : -17.80,
		"longitude" : -63.17,
		"city" : "Santa Cruz",
		"country" : "Bolivia",
		"icao" : "\\\\N",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7260,
		"name" : "All Airports",
		"code" : "STO",
		"latitude" : 59.32,
		"longitude" : 18.08,
		"city" : "Stockholm",
		"country" : "Sweden",
		"icao" : "\\\\N",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7480,
		"name" : "All Airports",
		"code" : "TCI",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Tenerife",
		"country" : "Spain",
		"icao" : "",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7578,
		"name" : "All Airports",
		"code" : "THR",
		"latitude" : 35.69,
		"longitude" : 51.31,
		"city" : "Tehran",
		"country" : "Iran",
		"icao" : "OIII",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7665,
		"name" : "All Airports",
		"code" : "TLV",
		"latitude" : 32.01,
		"longitude" : 34.89,
		"city" : "Tel Aviv",
		"country" : "Israel",
		"icao" : "LLBG",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7740,
		"name" : "All Airports",
		"code" : "TPA",
		"latitude" : 27.98,
		"longitude" : -82.53,
		"city" : "Tampa",
		"country" : "USA",
		"icao" : "KTPA",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7742,
		"name" : "All Airports",
		"code" : "TPE",
		"latitude" : 25.08,
		"longitude" : 121.23,
		"city" : "Taipei",
		"country" : "Taiwan",
		"icao" : "RCTP",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 7882,
		"name" : "All Airports",
		"code" : "TYO",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Tokyo",
		"country" : "Japan",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 8109,
		"name" : "All Airports",
		"code" : "VCE",
		"latitude" : 45.51,
		"longitude" : 12.35,
		"city" : "Venice",
		"country" : "Italy",
		"icao" : "LIPZ",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 8274,
		"name" : "All Airports",
		"code" : "WAS",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Washington",
		"country" : "USA",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 8302,
		"name" : "All Airports",
		"code" : "WDH",
		"latitude" : -22.49,
		"longitude" : 17.46,
		"city" : "Windhoek",
		"country" : "Namibia",
		"icao" : "FYWV",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 8767,
		"name" : "All Airports",
		"code" : "YEA",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Edmonton",
		"country" : "Canada",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 8911,
		"name" : "All Airports",
		"code" : "YMQ",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Montreal",
		"country" : "Canada",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 8951,
		"name" : "All Airports",
		"code" : "YOW",
		"latitude" : 45.32,
		"longitude" : -75.67,
		"city" : "Ottawa",
		"country" : "Canada",
		"icao" : "CYOW",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	},
	{
		"id" : 9055,
		"name" : "All Airports",
		"code" : "YTO",
		"latitude" : 0.00,
		"longitude" : 0.00,
		"city" : "Toronto",
		"country" : "Canada",
		"icao" : "NULL",
		"status" : true,
		"is_deleted" : false,
		"parent_id" : 0
	}
]
